"""Render operator-owned ``vmcp.toml`` for a Gateway (pure data, no I/O)."""

from __future__ import annotations

from vmcp_operator.domain.models.gateway import (
    AdminAuthMode,
    AuthProvider,
    GatewayDesired,
)


def render_gateway_config(gateway: GatewayDesired) -> str:
    """Produce a deterministic vmcp.toml matching vmcp ≥1.2 Settings shape."""
    public_base = f"https://{gateway.public_route.hostname}"
    lines: list[str] = [
        "# Generated by vmcp-operator — do not edit by hand.",
        'host = "0.0.0.0"',
        "port = 8080",
        'mcp_path = "/mcp"',
        f'public_base_url = "{_toml_str(public_base)}"',
        'registry_path = "/config/registry.json"',
        'lock_path = "/state/tools.lock.json"',
        'spec_dir = "/config/specs"',
        'skills_dir = "/state/skills"',
        "",
        "[gql]",
        f"max_depth = {gateway.gql.max_depth}",
        f"max_complexity = {gateway.gql.max_complexity}",
        "",
        "[proxy]",
        f"enabled = {_toml_bool(gateway.proxy.enabled)}",
        f'mcp_path = "{_toml_str(gateway.proxy.path)}"',
        "",
        "[tasks]",
        f"enabled = {_toml_bool(gateway.tasks.enabled)}",
        'db_path = "/state/tasks.db"',
        f"max_concurrent = {gateway.tasks.max_concurrent}",
        "",
        "[auth]",
        f"enabled = {_toml_bool(gateway.auth.enabled)}",
        f'provider = "{gateway.auth.provider.value}"',
        # Secrets are injected via env (master password) / mounted file (tokens).
        'tokens_file = "/secrets/tokens.json"',
        'clients_db_path = "/state/clients.db"',
        'jwks_private_key_pem_path = "/state/jwks.pem"',
        "",
        "[auth.admin]",
        f'mode = "{gateway.auth.admin.mode.value}"',
    ]
    if gateway.auth.admin.required_groups:
        groups = ", ".join(f'"{_toml_str(g)}"' for g in gateway.auth.admin.required_groups)
        lines.append(f"required_groups = [{groups}]")

    if gateway.auth.provider == AuthProvider.AUTHENTIK or (
        gateway.auth.admin.mode == AdminAuthMode.AUTHENTIK
    ):
        ak = gateway.auth.authentik
        lines.extend(
            [
                "",
                "[auth.authentik]",
                f'issuer = "{_toml_str(ak.issuer)}"',
                f'jwks_url = "{_toml_str(ak.jwks_url)}"',
                f"accept_bearer = {_toml_bool(ak.accept_bearer)}",
                f"forward_auth = {_toml_bool(ak.forward_auth)}",
                f'username_header = "{_toml_str(ak.username_header)}"',
                f'groups_header = "{_toml_str(ak.groups_header)}"',
                f'groups_claim = "{_toml_str(ak.groups_claim)}"',
                f'forward_auth_secret_header = "{_toml_str(ak.forward_auth_secret_header)}"',
            ]
        )
        if ak.audiences:
            aud = ", ".join(f'"{_toml_str(a)}"' for a in ak.audiences)
            lines.append(f"audiences = [{aud}]")
        if ak.trusted_proxies:
            proxies = ", ".join(f'"{_toml_str(p)}"' for p in ak.trusted_proxies)
            lines.append(f"trusted_proxies = [{proxies}]")
        if ak.group_scopes:
            # Inline TOML table: { "group" = "scope a scope b", … }
            scopes = ", ".join(
                f'"{_toml_str(group)}" = "{_toml_str(scopes)}"'
                for group, scopes in ak.group_scopes
            )
            lines.append(f"group_scopes = {{ {scopes} }}")
        # forward_auth_secret comes from env when SecretRef is set.

    lines.append("")
    return "\n".join(lines)


def _toml_bool(value: bool) -> str:
    return "true" if value else "false"


def _toml_str(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
