[package]
name = "vmcp-op-pyo3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_kernel"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["extension-module"] }
vmcp-op-core = { path = "../vmcp-op-core" }

[lints.rust]
unsafe_code = "forbid"
